<a href="https://colab.research.google.com/github/uroojhanif78-coder/Pandas/blob/pandas-hands-on/Pandas_task_1_to_5_%2B_Hands_On.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# task 1: "create students data frame"

import pandas as pd

data = {
    "Name" : ["ali","sara","ahmed","ayesha","zain"],
    "Marks" :[70,85,60,95,45]
}
df = pd.DataFrame(data)
print(df)
Marks=df["Marks"]
print(Marks.mean())
print(Marks.max())
print(Marks.min())


name =df["Name"]
print(name.count())

     Name  Marks
0     ali     70
1    sara     85
2   ahmed     60
3  ayesha     95
4    zain     45
71.0
95
45
5

In [ ]:
# task 2: "students whose marks are greater & less than 50"

print(df[df['Marks'] >= 50])
print(df[df['Marks'] <= 50])

     Name  Marks
0     ali     70
1    sara     85
2   ahmed     60
3  ayesha     95
   Name  Marks
4  zain     45

In [ ]:
# task 3: "Add a new column"

df["cities"]=["karachi","lahore","islamabad","faislabad","rawalpindi"]
print("only Karachi Students:")
print(df[df['cities'] == "karachi"])

only Karachi Students:
  Name  Marks   cities
0  ali     70  karachi

In [ ]:
# task 4: "Find the average marks of each course using groupby()"

data = {

    "Name": ["Ali","sara","ahmed","ayesha","zain"],
    "Course":["AI","Web","AI","Web","AI"],
    "Marks":[70,60,80,50,90]

}
df = pd.DataFrame(data)
result=df.groupby("Course")["Marks"].mean()
print(result)

Course
AI     80.0
Web    55.0
Name: Marks, dtype: float64

In [ ]:
#task 5: "Create a DataFrame containing some missing marks"
import pandas as pd


data = {

    "Name":["Ali","Sara","Ahmed","Ayesha","Zain"],
    "Marks":[80,None,70,None,90]
}


print(df.isnull())
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
print(df)

    Name  Marks
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False
     Name  Marks
0     Ali   80.0
1    Sara   80.0
2   Ahmed   70.0
3  Ayesha   80.0
4    Zain   90.0

In [ ]:
import pandas as pd
# Making data set

data = {
    "Name": ["Ali", "Sara", "Ahmed", "Hina", "Usman", "Ayesha","Bilal", "Hamnah","Hasnain","Zain"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance","Sales","HR","IT","Welfare"],
    "Age": [25, 28, 30, 35, 27, 32,34, 30, 28, 36],
    "Salary": [50000, 65000, 68000, 70000, 45000, 75000, 90000, 60000, 90000, 85000],
    "City": ["Karachi", "Lahore", "Sialkot", "Lahore", "Islamabad", "Sialkot", "Karachi", "Islamabad", "Karachi", "Lahore"]
}

df = pd.DataFrame(data)
df

      Name Department  Age  Salary       City
0      Ali         IT   25   50000    Karachi
1     Sara         HR   28   65000     Lahore
2    Ahmed         IT   30   68000    Sialkot
3     Hina    Finance   35   70000     Lahore
4    Usman         HR   27   45000  Islamabad
5   Ayesha    Finance   32   75000    Sialkot
6    Bilal      Sales   34   90000    Karachi
7   Hamnah         HR   30   60000  Islamabad
8  Hasnain         IT   28   90000    Karachi
9     Zain    Welfare   36   85000     Lahore

In [ ]:
print(df.head(2))

   Name Department  Age  Salary     City
0   Ali         IT   25   50000  Karachi
1  Sara         HR   28   65000   Lahore

In [ ]:
print(df.tail())

      Name Department  Age  Salary       City
5   Ayesha    Finance   32   75000    Sialkot
6    Bilal      Sales   34   90000    Karachi
7   Hamnah         HR   30   60000  Islamabad
8  Hasnain         IT   28   90000    Karachi
9     Zain    Welfare   36   85000     Lahore

In [ ]:
df.shape

(10, 5)

In [ ]:
df.dtypes

Name          object
Department    object
Age            int64
Salary         int64
City          object
dtype: object

In [ ]:
df.describe()

             Age        Salary
count  10.000000     10.000000
mean   30.500000  69800.000000
std     3.659083  15647.506014
min    25.000000  45000.000000
25%    28.000000  61250.000000
50%    30.000000  69000.000000
75%    33.500000  82500.000000
max    36.000000  90000.000000

In [ ]:
df["Name"]

0        Ali
1       Sara
2      Ahmed
3       Hina
4      Usman
5     Ayesha
6      Bilal
7     Hamnah
8    Hasnain
9       Zain
Name: Name, dtype: object

In [ ]:
df["Salary"]

0    50000
1    65000
2    68000
3    70000
4    45000
5    75000
6    90000
7    60000
8    90000
9    85000
Name: Salary, dtype: int64

In [ ]:
df[["Name","Salary"]]

      Name  Salary
0      Ali   50000
1     Sara   65000
2    Ahmed   68000
3     Hina   70000
4    Usman   45000
5   Ayesha   75000
6    Bilal   90000
7   Hamnah   60000
8  Hasnain   90000
9     Zain   85000

In [ ]:
df.loc[2 ,["Age"]]

Age    30
Name: 2, dtype: object

In [ ]:
print(df.iloc[1,3])

65000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     object
 1   Department  10 non-null     object
 2   Age         10 non-null     int64
 3   Salary      10 non-null     int64
 4   City        10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [ ]:
df[df["Department"] == "IT"]

      Name Department  Age  Salary     City
0      Ali         IT   25   50000  Karachi
2    Ahmed         IT   30   68000  Sialkot
8  Hasnain         IT   28   90000  Karachi

In [ ]:
df.iloc[1:3 ,[0,2]]

    Name  Age
1   Sara   28
2  Ahmed   30

In [ ]:
import pandas as pd
# Adding a new column

df["Bonus"]= df["Salary"]*0.10
df

      Name Department  Age  Salary       City   Bonus
0      Ali         IT   25   50000    Karachi  5000.0
1     Sara         HR   28   65000     Lahore  6500.0
2    Ahmed         IT   30   68000    Sialkot  6800.0
3     Hina    Finance   35   70000     Lahore  7000.0
4    Usman         HR   27   45000  Islamabad  4500.0
5   Ayesha    Finance   32   75000    Sialkot  7500.0
6    Bilal      Sales   34   90000    Karachi  9000.0
7   Hamnah         HR   30   60000  Islamabad  6000.0
8  Hasnain         IT   28   90000    Karachi  9000.0
9     Zain    Welfare   36   85000     Lahore  8500.0

In [ ]:
# updating values

df["Salary"] = df["Salary"]+5500
df

      Name Department  Age  Salary       City   Bonus
0      Ali         IT   25   55500    Karachi  5000.0
1     Sara         HR   28   70500     Lahore  6500.0
2    Ahmed         IT   30   73500    Sialkot  6800.0
3     Hina    Finance   35   75500     Lahore  7000.0
4    Usman         HR   27   50500  Islamabad  4500.0
5   Ayesha    Finance   32   80500    Sialkot  7500.0
6    Bilal      Sales   34   95500    Karachi  9000.0
7   Hamnah         HR   30   65500  Islamabad  6000.0
8  Hasnain         IT   28   95500    Karachi  9000.0
9     Zain    Welfare   36   90500     Lahore  8500.0

In [ ]:
# Deleting a column
df = df.drop("Age", axis=1)
df

      Name Department  Salary       City   Bonus
0      Ali         IT   55500    Karachi  5000.0
1     Sara         HR   70500     Lahore  6500.0
2    Ahmed         IT   73500    Sialkot  6800.0
3     Hina    Finance   75500     Lahore  7000.0
4    Usman         HR   50500  Islamabad  4500.0
5   Ayesha    Finance   80500    Sialkot  7500.0
6    Bilal      Sales   95500    Karachi  9000.0
7   Hamnah         HR   65500  Islamabad  6000.0
8  Hasnain         IT   95500    Karachi  9000.0
9     Zain    Welfare   90500     Lahore  8500.0

In [ ]:
# Deleting a row
df = df.drop(2,axis = 0)
print(df)

      Name Department  Salary       City   Bonus
1     Sara         HR   70500     Lahore  6500.0
4    Usman         HR   50500  Islamabad  4500.0
5   Ayesha    Finance   80500    Sialkot  7500.0
6    Bilal      Sales   95500    Karachi  9000.0
7   Hamnah         HR   65500  Islamabad  6000.0
8  Hasnain         IT   95500    Karachi  9000.0
9     Zain    Welfare   90500     Lahore  8500.0

In [ ]:
# missing value

df.isnull()

    Name  Department  Salary   City  Bonus
1  False       False   False  False  False
4  False       False   False  False  False
5  False       False   False  False  False
6  False       False   False  False  False
7  False       False   False  False  False
8  False       False   False  False  False
9  False       False   False  False  False

In [ ]:
df.duplicated()

1    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
# sorting values
df.sort_values("Salary", ascending=True)

      Name Department  Salary       City   Bonus
4    Usman         HR   50500  Islamabad  4500.0
7   Hamnah         HR   65500  Islamabad  6000.0
1     Sara         HR   70500     Lahore  6500.0
5   Ayesha    Finance   80500    Sialkot  7500.0
9     Zain    Welfare   90500     Lahore  8500.0
6    Bilal      Sales   95500    Karachi  9000.0
8  Hasnain         IT   95500    Karachi  9000.0

In [ ]:
df.sort_values("Salary", ascending=False)

      Name Department  Salary       City   Bonus
6    Bilal      Sales   95500    Karachi  9000.0
8  Hasnain         IT   95500    Karachi  9000.0
9     Zain    Welfare   90500     Lahore  8500.0
5   Ayesha    Finance   80500    Sialkot  7500.0
1     Sara         HR   70500     Lahore  6500.0
7   Hamnah         HR   65500  Islamabad  6000.0
4    Usman         HR   50500  Islamabad  4500.0